schema: "src/lib/graphql/**/*.graphqls"
schemaEntrypoint: "src/lib/graphql/schema/type-defs.graphqls"
documents: "src/lib/graphql/**/*.graphql"
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
